sudo: required
language: python
services: docker

env:
  matrix:
    - distribution: Ubuntu
      distribution_version: xenial
      init: /lib/systemd/systemd
      run_opts: "--privileged --volume=/sys/fs/cgroup:/sys/fs/cgroup:ro"
    - distribution: EL
      distribution_version: 7
      init: /usr/lib/systemd/systemd
      run_opts: "--privileged --volume=/sys/fs/cgroup:/sys/fs/cgroup:ro"
    - distribution: EL
      distribution_version: "6"
      init: /sbin/init
      run_opts: ""

before_install:
  # Pull container from Docker Hub.
  - 'docker pull ansiblecheck/ansiblecheck:${distribution,,}-${distribution_version}'

script:
  - container_id=$(mktemp)
  # Start The Built Container In The Background
  - 'docker run --detach --volume="${PWD}":/etc/ansible/roles/role_under_test:ro ${run_opts} ansiblecheck/ansiblecheck:"${distribution,,}"-"${distribution_version}" "${init}" > "${container_id}"'
  # Install requirements, Uncomment if needed
  #- 'docker exec "$(cat ${container_id})" env ANSIBLE_FORCE_COLOR=true ansible-galaxy install -v -r /etc/ansible/roles/role_under_test/requirements.yml'

  # Ansible version check.
  - 'docker exec --tty "$(cat ${container_id})" env ANSIBLE_FORCE_COLOR=true ansible --version'
  # Ansible syntax check.
  - 'docker exec --tty "$(cat ${container_id})" env ANSIBLE_FORCE_COLOR=true ansible-playbook /etc/ansible/roles/role_under_test/tests/test.yml --syntax-check'

  # Test role.
  - 'docker exec "$(cat ${container_id})" env ANSIBLE_FORCE_COLOR=true ansible-playbook --connection=local -i /etc/ansible/roles/role_under_test/tests/inventory /etc/ansible/roles/role_under_test/tests/test.yml'

  # Test Idempotence
  - idempotence=$(mktemp)
  - docker exec "$(cat ${container_id})" env ANSIBLE_FORCE_COLOR=true ansible-playbook --connection=local -i /etc/ansible/roles/role_under_test/tests/inventory /etc/ansible/roles/role_under_test/tests/test.yml | tee -a ${idempotence}
  - >
    tail ${idempotence}
    | grep -q 'changed=0.*failed=0'
    && (echo 'Idempotence test: pass' && exit 0)
    || (echo 'Idempotence test: fail' && exit 1)

  # Run role test suite
  # Add your own tests depending on your $ROLE
  - echo "=======> Starting output tests"


#notifications:
#  webhooks: https://galaxy.ansible.com/api/v1/notifications/
